### ISSUE TITLE
Crash when calling BP events from console

### ISSUE THREAD

**Issue by nlamartina** [AndrisBorbas/QuickCommands#1]
I have multiple BP custom events saved in my root level that I normally call in the console with "ce BlahBlahEvent". If I use QuickCommands to try and post any of these "ce" commands, UE4 crashes. All other console commands are working fine. I installed QuickCommands from the Unreal Marketplace and am using UE 4.21.
![example](https://user-images.githubusercontent.com/11888535/90421218-0ce89f80-e087-11ea-8d7a-9da8dd25a915.PNG)

**Comment by AndrisBorbas** [comment]
Could you send a crash report while I try to reproduce it?

**Comment by nlamartina** [comment]
Done. I'm assuming I do that through the editor crash dialog that appears afterward. Let me know if you need something different.

**Comment by AndrisBorbas** [comment]
Uh, i would need that report so you might have to copy paste it somehow, pastebin or something :D

**Comment by AndrisBorbas** [comment]
I managed to recreate it, and have some idea of whats causing it, but no idea if i am able to fix it

**Comment by AndrisBorbas** [comment]
Welp, I fixed it somehow 😅
I'll update the repo, but depending on Epic, the official plugin might take a while to update, so your best bet is installing manually from the repo.

**Comment by nlamartina** [comment]
Outstanding, the fix works. Thanks very much for such a rapid turnaround time!
