### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by colejd** [AndrisBorbas/QuickCommands#6]
Hi there!

Just curious if you've thought about adding a license to this project. Without one, open-source can't benefit from this plugin.

Thanks!

**Comment by AndrisBorbas** [comment]
Hi!
Haven't thought about it really, I thought that by it being here and open source anyone could use it.
You recommend any licenses?

**Comment by colejd** [comment]
In the US, if you don't provide a license, you retain the copyright and others can't use your code in open source projects without fear of a potential lawsuit. Not sure how it is outside the country, haha. But either way, a license explicitly grants permission for usage. 

I like the MIT license, which basically says "you can use my code however you want, but you can't sue me if something breaks." [Here's some documentation on setting up the license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) - when you go to select your license, you can read about what each one does.

**Comment by AndrisBorbas** [comment]
Alright, thanks for the heads up, I'm gonna add one

**Comment by colejd** [comment]
Thanks!
