### ISSUE TITLE
Some console commands are not working

### ISSUE THREAD

**Issue by Ares9323** [AndrisBorbas/QuickCommands#7]
Some commands I tried that are not working if called from the plugin's window, but they work from the console and if called from the "run console command" node:

- viewmode collisionpawn
- viewmode collisionvis
- viewmode hlodcoloration
- viewmode lodcoloration
- viewmode lightcomplexity
- viewmode lightingonly
- viewmode lit
- viewmode lit_detaillighting
- viewmode shadercomplexity
- viewmode unlit
- viewmode wireframe

**Comment by AndrisBorbas** [comment]
I'll check it out when I have time

**Comment by AndrisBorbas** [comment]
Sorry I just got around to this, ~~but these also don't work from the built in console in ue5 for me~~ nevermind, it works from console, but I think this isn't an actuall command and just handled differently, I'll check

**Comment by Ares9323** [comment]
Don't worry, I solved it months ago, these commands work only if the game is running, to change them in the editor I had to dig through the source code and trigger other specific functions. UE5 changed something and console commands sometimes require a WorldContextObject in order to work correctly:
![image](https://user-images.githubusercontent.com/46932745/212928798-71b5e796-f17b-46e1-9083-51a64ae7b466.png)

**Comment by AndrisBorbas** [comment]
Ah I see. I think I found it though, this blueprint node first tries to execute it on a player controller if available and if not only then goes to the engine to execute the command and in there I didn't find viewmode handling.

I'll try the same

**Comment by Ares9323** [comment]
Set view mode is a custom function I created in C++, the viewmode enum is not exposed to blueprints so I had to use a different approach

**Comment by AndrisBorbas** [comment]
I managed to fix it, but it will only be in the 5.1 marketplace version
*Edit: and here on GitHub of course
